### PR TITLE
fix falsy children such as integer 0 are not rendered at all

### PR DESCRIPTION
**Pull request by rekotiira**

### CODE REVIEW

**Comment by raimohanska** [comment]
Thanks! Will merge. Can you come up with a test case for the fix too?

**Comment by polytypic** [comment]
Here is a [test](https://github.com/calmm-js/karet/commit/5ed65caeb387a541c02fb4781a841cad6fc256ce) for it.

**Comment by rekotiira** [comment]
I'll add the test.

**Comment by raimohanska** [comment]
Boom, that was fast!

**Comment by raimohanska** [comment]
baret@1.0.5

**Pull request merged**
